background = '#000105'
foreground = '#F8F5F8'
text = '#F8F5F8'
cursor = '#F8F5F8'
black   = '#000716'
red     = '#8F6678'
green   = '#A7577E'
yellow  = '#367C9B'
blue    = '#7B6E72'
magenta = '#9B724A'
cyan    = '#B1AAB0'
white   = '#EDE8EC'
black   = '#A5A2A5'
red     = '#B1738E'
green   = '#DA6AA1'
yellow  = '#3B9EC9'
blue    = '#A49398'
magenta = '#CF9963'
cyan    = '#ECE3EB'
white   = '#EDE8EC'
