background = '#00090F'
foreground = '#FBF4F7'
text = '#FBF4F7'
cursor = '#FBF4F7'
black   = '#00090F'
red     = '#002C4D'
green   = '#B63F77'
yellow  = '#97641E'
blue    = '#3B9EC9'
magenta = '#67C076'
cyan    = '#F4DFE7'
white   = '#F1E7EB'
black   = '#A9A1A4'
red     = '#002C4D'
green   = '#B63F77'
yellow  = '#97641E'
blue    = '#3B9EC9'
magenta = '#67C076'
cyan    = '#F4DFE7'
white   = '#F1E7EB'
