[colors]
foreground = "{{foreground}}"
background = "{{background}}"
cursor_bg = "{{color0}}"
cursor_border = "{{color9}}"
cursor_fg = "{{cursor}}"
selection_bg = "{{color3}}"
selection_fg = "{{foreground}}"
ansi = ["{{color0}}", "{{color1}}", "{{color2}}", "{{color3}}", "{{color4}}", "{{color5}}", "{{color6}}", "{{color7}}"]
brights = ["{{color8}}", "{{color9}}", "{{color10}}", "{{color11}}", "{{color12}}", "{{color13}}", "{{color14}}", "{{color15}}"]
compose_cursor = "#ffffff"

[metadata]
name = 'wallust'
