[config]

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar-colors.css'
output_path = '~/.config/waybar/colors-matugen.css'
# post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/shared/colors.rasi'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty-colors.conf'
output_path = '~/.config/ghostty/themes/matugen.conf'

[templates.nyaa]
input_path = '~/.config/matugen/templates/nyaa-colors.toml'
output_path = '~/.config/nyaa/themes/Material-You.toml'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors'
output_path = '~/.config/cava/config'
post_hook = 'pkill -USR2 cava'

[templates.hypr]
input_path = '~/.config/matugen/templates/hypr-colors.conf'
output_path = '~/.config/hypr/themes/colors-matugen.conf'
# post_hook = 'hyprctl reload'

# [templates.neovim]
# input_path = '~/.config/matugen/templates/neovim-colors.vim'

# output_path = '~/.cache/wal/colors-wal.vim'
# [templates.bat]
# input_path = '{{custom.templates}}/bat-colors.tmTheme'
# output_path = '~/.config/bat/themes/matugen.tmTheme'
# hook = "{{custom.hooks}}/bat-hook.sh"

# [templates.dunst]
# input_path = '~/.config/matugen/templates/dunstrc-colors'
# output_path = '~/.config/dunst/dunstrc'
# post_hook = 'killall dunst && dunst & disown'
