name = "Material-You"
bg = "Reset"
fg = "#ffb3af"
border = "Rounded"
border_color = "#733331"
border_focused_color = "#ffb3af"
hl_bg = "#0f0f0f"
solid_bg = "White"
solid_fg = "Black"
success = "Green"
error = "Red"
info = "Green"
warning = "Yellow"
