[colors]
foreground = "#FFF5C7"
background = "#0A0B0A"
cursor_bg = "#0A0B0A"
cursor_border = "#7D680B"
cursor_fg = "#FFF5C7"
selection_bg = "#62739E"
selection_fg = "#FFF5C7"
ansi = ["#0A0B0A", "#7D680B", "#BF476A", "#62739E", "#A0A69A", "#FABABA", "#FFE25F", "#F6E8A6"]
brights = ["#ADA275", "#7D680B", "#BF476A", "#62739E", "#A0A69A", "#FABABA", "#FFE25F", "#F6E8A6"]
compose_cursor = "#ffffff"

[metadata]
name = 'wallust'
