[colors]
foreground = "#FBF4F7"
background = "#00090F"
cursor_bg = "#00090F"
cursor_border = "#002C4D"
cursor_fg = "#FBF4F7"
selection_bg = "#97641E"
selection_fg = "#FBF4F7"
ansi = ["#00090F", "#002C4D", "#B63F77", "#97641E", "#3B9EC9", "#67C076", "#F4DFE7", "#F1E7EB"]
brights = ["#A9A1A4", "#002C4D", "#B63F77", "#97641E", "#3B9EC9", "#67C076", "#F4DFE7", "#F1E7EB"]
compose_cursor = "#ffffff"

[metadata]
name = 'wallust'
