[window]
opacity = 0.25

[colors.primary]
background = '#06060A'
foreground = '#F9F6EF'

[colors.cursor]
text = '#F9F6EF'
cursor = '#F9F6EF'

[colors.normal]
black   = '#06060A'
red     = '#A56E4C'
green   = '#AF7776'
yellow  = '#B47A37'
blue    = '#678C94'
magenta = '#9E898E'
cyan    = '#B2AC9E'
white   = '#EEEAE0'

[colors.bright]
black   = '#A6A49D'
red     = '#DC9365'
green   = '#E99E9D'
yellow  = '#F0A24A'
blue    = '#89BBC5'
magenta = '#D2B7BD'
cyan    = '#EDE6D2'
white   = '#EEEAE0'
