name = "Material-You"
bg = "Reset"
fg = "{{colors.primary.default.hex}}"
border = "Rounded"
border_color = "{{colors.primary_container.default.hex}}"
border_focused_color = "{{colors.primary.default.hex}}"
hl_bg = "#0f0f0f"
solid_bg = "White"
solid_fg = "Black"
success = "Green"
error = "Red"
info = "Green"
warning = "Yellow"
